### ISSUE TITLE
[enhancement] 在 explore 頁面點擊收藏會觸發所有 refetch

### ISSUE THREAD

**Issue by SimoneCheng** [KellyCHI22/HowTo#1]
## Description

如題，在 explore 點擊收藏文章的時候，會觸發所有的 refetch，覺得這邊可以優化一下，詳細操作流程可以參考 screenshot。

## Screenshot

https://github.com/KellyCHI22/HowTo/assets/58110624/a0f5e3f0-b62e-49a3-9cfe-4b5fe07655ba

**Comment by KellyCHI22** [comment]
Solved with changing 'isFetching' to 'isLoading' in RTK query hooks.

Reference: https://stackoverflow.com/questions/75401477/reasons-for-using-isloading-or-isfetching-in-react-query
